services:
  pihole:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: pihole/pihole
    restart: unless-stopped
    environment:
      TZ: ${JARVIS_TZ}
      WEBTHEME: default-darker
      WEBPASSWORD: ${JARVIS_PASSWORD}
      PIHOLE_DNS_: ${JARVIS_GOOGLE_DNS}
      FTLCONF_LOCAL_IPV4: ${JARVIS_STATIC_IP}
      VIRTUAL_HOST: pi.hole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
    volumes:
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}:/etc/pihole
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/dnsmasq.d:/etc/dnsmasq.d
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.myjarvis.in`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
    networks:
      - proxy

networks:
  proxy:
    external: true