services:
  traefik:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: traefik
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.${JARVIS_CERT_RESOLVER}.acme.dnschallenge=true
      - --certificatesresolvers.${JARVIS_CERT_RESOLVER}.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.${JARVIS_CERT_RESOLVER}.acme.email=${JARVIS_USER_EMAIL}
      - --certificatesresolvers.${JARVIS_CERT_RESOLVER}.acme.storage=/${JARVIS_CERT_RESOLVER}/acme.json
      - --log.level=DEBUG
    environment:
      CF_DNS_API_TOKEN: ${JARVIS_CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}:/etc/traefik
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/${JARVIS_CERT_RESOLVER}:/${JARVIS_CERT_RESOLVER}
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${JARVIS_CONTAINER_NAME}.myjarvis.in`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=${JARVIS_CERT_RESOLVER}
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    name: proxy