version: "3.8"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ}
      WEBPASSWORD: 112233
      WEBTHEME: default-darker
      PIHOLE_DOMAIN: pi.hole
      DHCP_ACTIVE: true
      DHCP_ROUTER: 192.168.0.1
      DHCP_START: 192.168.0.2
      DHCP_END: 192.168.0.199
    volumes:
      - ${ROOT}/.config/pihole:/etc/pihole
      - ${ROOT}/.config/pihole/dnsmasq.d:/etc/dnsmasq.d
    