services:
  caddy:
    image: caddy
    container_name: caddy
    environment:
      PUID: ${JARVIS_PUID}
      PGID: ${JARVIS_PGID}
      JARVIS_USER_EMAIL: ${JARVIS_USER_EMAIL}
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 2019:2019
    volumes:
      - ${JARVIS_CONFIG_ROOT}/caddy:/etc/caddy
      - ${JARVIS_CONFIG_ROOT}/caddy/data:/data
      - ${JARVIS_CONFIG_ROOT}/caddy/config:/config
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    name: proxy