services:
  oauth2-proxy:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: quay.io/oauth2-proxy/oauth2-proxy
    ports:
      - "4180:4180"
    volumes:
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/oauth2-proxy.cfg:/etc/oauth2-proxy/oauth2-proxy.cfg
    environment:
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_CLIENT_ID=<github_client_id>
      - OAUTH2_PROXY_CLIENT_SECRET=<github_client_secret>
      - OAUTH2_PROXY_COOKIE_SECRET=<cookie_secret>
      - OAUTH2_PROXY_REDIRECT_URL=https://yourdomain.com/oauth2/callback
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
    networks:
      - proxy

networks:
  proxy:
    external: true