---
- name: Setup Local Environment
  hosts: local
  connection: local
  gather_facts: true
  tasks:
      - name: Install Ansible Requirements
        command: ansible-galaxy collection install -r requirements.yml --upgrade
        register: galaxy_install
        changed_when: "'Installing' in galaxy_install.stdout"

      - name: Environment Setup
        include_tasks: tasks/env.yml

- name: Deploy to Remote Proxmox
  hosts: proxmox
  gather_facts: false
  pre_tasks:
      - name: Restore Environment Variables
        set_fact:
            env: '{{ hostvars["local"]["env"] }}'
        no_log: true

  tasks:
      - name: Execute System Tasks
        include_tasks: 'tasks/system/{{ item }}.yml'
        loop:
            - health
            - update
            - automount
            - security

      - name: Deploy Instances
        include_tasks: 'tasks/instances/{{ item }}.yml'
        loop:
            - traefik_lxc
            # - home_vm
            - docker_lxc
            - storage_lxc
            - jellyfin_lxc
            - qbittorrent_lxc
            - pihole_lxc
