---
- vars:
      app_name: docker
  block:
      - name: '{{ app_name | upper }}: Add APT Repository'
        shell: |
            {{ lxc_exec }} <<'EOF'
            [ -f /etc/apt/sources.list.d/docker.list ] && exit 0
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
            chmod a+r /etc/apt/keyrings/docker.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
            echo CHANGED
            EOF
        register: docker_repo
        changed_when: "'CHANGED' in docker_repo.stdout"

      - name: '{{ app_name | upper }}: Install Engine'
        include_tasks: lxc_apt.yml
        vars:
            lxc_apt:
                - docker-ce
                - docker-ce-cli
                - containerd.io
                - docker-buildx-plugin
                - docker-compose-plugin

      - name: '{{ app_name | upper }}: Enable and Start Service'
        include_tasks: lxc_service.yml
        vars:
            lxc_service:
                name: docker
