- name: '{{ app_name | upper }}: Enable and Start {{ lxc_service.name }}'
  shell: |
      {{ lxc_exec }} <<'EOF'
      {% if lxc_service.restart | default(false) | bool %}
      systemctl daemon-reload
      systemctl enable -q {{ lxc_service.name }}
      systemctl restart {{ lxc_service.name }}
      echo CHANGED
      exit 0
      {% endif %}
      systemctl is-enabled -q {{ lxc_service.name }} && systemctl is-active -q {{ lxc_service.name }} && exit 0
      systemctl daemon-reload
      systemctl enable -q --now {{ lxc_service.name }}
      echo CHANGED
      EOF
  register: service_result
  changed_when: "'CHANGED' in service_result.stdout"
