---
- vars:
      app_name: cloudflared
      app_dir: '{{ apps_dir }}/cloudflared'
      apt_repos:
          - { name: cloudflared, uri: 'https://pkg.cloudflare.com/cloudflared', suite: any, key: 'https://pkg.cloudflare.com/cloudflare-main.gpg' }
      apt_packages:
          - cloudflared
  block:
      - name: '{{ app_name | upper }}: Install Package'
        ansible.builtin.include_tasks: '{{ lib }}/apt.yml'

      - name: '{{ app_name | upper }}: Read Version'
        ansible.builtin.command: dpkg-query -W -f=${Version} cloudflared
        register: cloudflared_version
        changed_when: false

      - name: '{{ app_name | upper }}: Configure Directory'
        ansible.builtin.file:
            path: '{{ app_dir }}'
            state: directory
            owner: '{{ user }}'
            group: '{{ user }}'

      - name: '{{ app_name | upper }}: Write Token File'
        ansible.builtin.copy:
            dest: '{{ app_dir }}/env'
            content: 'TUNNEL_TOKEN={{ env.RITIK_CF_TUNNEL_TOKEN }}'
            owner: root
            group: root
            mode: '0600'
        no_log: true
        register: cloudflared_env

      - name: '{{ app_name | upper }}: Configure Service'
        ansible.builtin.include_tasks: '{{ lib }}/service.yml'
        vars:
            service:
                name: cloudflared
                restart: '{{ cloudflared_env is changed }}'
                content: |
                    [Unit]
                    Description=Cloudflare Tunnel
                    After=network-online.target
                    Wants=network-online.target

                    [Service]
                    Type=notify
                    EnvironmentFile={{ app_dir }}/env
                    Environment=CLOUDFLARED_VERSION={{ cloudflared_version.stdout }}
                    ExecStart=/usr/bin/cloudflared --no-autoupdate tunnel run
                    Restart=on-failure
                    RestartSec=5s

                    [Install]
                    WantedBy=multi-user.target
