name: ${JARVIS_CONTAINER_NAME}
services:
  traefik:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    entrypoint: ["/bin/sh", "-c"]
    command: ["touch /data/acme.json && chmod 600 /data/acme.json && exec traefik --configFile=/config/traefik.yml"]
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: ${JARVIS_TZ}
      DOMAINNAME: ${JARVIS_DOMAIN}
      CF_DNS_API_TOKEN: ${JARVIS_CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${JARVIS_CONFIGS}/${JARVIS_CONTAINER_NAME}:/config
      - ${JARVIS_CONFIGS}/${JARVIS_CONTAINER_NAME}/data:/data
      - ${JARVIS_CONFIGS}/${JARVIS_CONTAINER_NAME}/rules:/rules
      - ${JARVIS_LOGS}/${JARVIS_CONTAINER_NAME}:/logs
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.${JARVIS_DOMAIN}`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.service=api@internal
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.middlewares=chain-auth@file
    extra_hosts: 
      host.docker.internal: host-gateway
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true