services:
  traefik:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - --api=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.domains[0].main=${JARVIS_DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${JARVIS_DOMAIN}
      - --entrypoints.websecure.http.tls.domains[1].main=${JARVIS_HOSTNAME}.local
      - --certificatesresolvers.${JARVIS_CERT_RESOLVER}.acme.dnschallenge=true
      - --certificatesresolvers.${JARVIS_CERT_RESOLVER}.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.${JARVIS_CERT_RESOLVER}.acme.email=${JARVIS_EMAIL}
      - --certificatesresolvers.${JARVIS_CERT_RESOLVER}.acme.storage=/${JARVIS_CERT_RESOLVER}/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --serversTransport.insecureSkipVerify=true
      - --log.level=DEBUG
    ports:
      - 80:80
      - 443:443
    environment:
      PUID: ${JARVIS_PUID}
      PGID: ${JARVIS_PGID}
      CF_DNS_API_TOKEN: ${JARVIS_CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}:/etc/traefik
      - ${JARVIS_CERT_RESOLVER}:/${JARVIS_CERT_RESOLVER}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.${JARVIS_DOMAIN}`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.middlewares=auth@docker
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.service=api@internal
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
      - traefik.http.services.${JARVIS_CONTAINER_NAME}.loadbalancer.server.port=80
    extra_hosts: 
      host.docker.internal: host-gateway
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

volumes:
  letsencrypt:
    external: true

networks:
  proxy:
    external: true