---
- name: 'UPDATE: Update Apt Cache'
  apt:
      update_cache: yes
      cache_valid_time: 86400

- name: 'UPDATE: Upgrade, Autoremove & Clean'
  apt:
      upgrade: yes
      autoremove: yes
      autoclean: yes
