---
- vars:
      app_name: update
  block:
      - name: '{{ app_name | upper }}: Update Apt Cache'
        apt:
            update_cache: yes
            cache_valid_time: 86400

      - name: '{{ app_name | upper }}: Upgrade, Autoremove & Clean'
        apt:
            upgrade: yes
            autoremove: yes
            autoclean: yes
