services:
  adguard:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: adguard/adguardhome
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${JARVIS_DRIVE_ROOT}/.${JARVIS_CONTAINER_NAME}/work:/opt/adguardhome/work
      - ${JARVIS_DRIVE_ROOT}/.${JARVIS_CONTAINER_NAME}/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 67:67/udp
      # - 68:68/udp
      - 6666:80/tcp
      # - 443:443/tcp
      # - 443:443/udp
      - 784:784/udp
      - 853:853/tcp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.${JARVIS_DOMAIN}`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.middlewares=auth@docker
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
      - traefik.http.services.${JARVIS_CONTAINER_NAME}.loadbalancer.server.port=80
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true