set -g mouse on
setw -g monitor-activity on
set -g visual-activity off
set -sg escape-time 0
set -g history-limit 50000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_path}:#{pane_current_command}"

set -g status-style "bg=#161616,fg=white"
set -g status-left "#{?@picker,#[range=user|sessions]#[fg=black#,bg=red#,bold] ✕ #[norange fg=white#,bg=#161616] #[range=user|newsession]#[fg=black#,bg=green#,bold] + new #[norange fg=white#,bg=#161616],#[range=user|sessions]#[fg=black#,bg=cyan#,bold] #{n:#{s/y.*//:#{S:x,y}}} #[norange fg=white#,bg=#161616]} "
set -g status-left-length 30
set -g status-right-length 100
set -g status-interval 5

setw -g window-status-format "#{?@picker,, #I:#W }"
setw -g window-status-current-format "#{?@picker,,#[fg=black#,bg=green#,bold] #I:#W #[fg=white#,bg=#161616]}"
setw -g window-status-style "fg=#d0d0d0"
setw -g window-status-activity-style "fg=yellow,bold"

set -g status-right "#{?@picker,,#{?client_prefix,#[fg=black#,bg=red#,bold] PFX #[fg=white#,bg=#161616] ,}#[fg=black#,bg=green#,bold] + #[fg=white#,bg=#161616] #[range=user|detach]#[fg=black#,bg=red#,bold] ✕ #[norange fg=white#,bg=#161616] }"

set-hook -g pane-mode-changed 'set -gF @picker "#{==:#{pane_mode},tree-mode}"'
bind -n MouseDown1StatusRight if -F '#{!=:#{@picker},1}' 'new-window -c "#{pane_current_path}"'
bind -n MouseDown1Status if -F '#{==:#{mouse_status_range},sessions}' { if -F '#{==:#{pane_mode},tree-mode}' 'send-keys q' 'choose-tree -Zs' } { if -F '#{==:#{mouse_status_range},newsession}' { send-keys q; command-prompt -p 'new session:' "new -A -s '%%'" } { if -F '#{==:#{mouse_status_range},detach}' 'detach-client' { if -F '#{!=:#{@picker},1}' 'select-window -t=' } } }
bind -n MouseDown3Status if -F '#{==:#{mouse_status_range},window}' "kill-window -t '{mouse}'"
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display-message "reloaded"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'ssh "~npm" "~pnpm" "~yarn" "~bun" "~node" "~python" "~uv" "~docker compose" "~make" "~go run"'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
run '~/.tmux/plugins/tpm/tpm'
