name: ${JARVIS_CONTAINER_NAME}
services:
  homeassistant:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: ghcr.io/home-assistant/home-assistant
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      TZ: ${JARVIS_TZ}
      PUID: ${JARVIS_PUID}
      PGID: ${JARVIS_PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}:/config