version: "3.8"
services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=5000
    volumes:
      - ${ROOT}/.config/qbittorrent:/config
      - ${ROOT}/Downloads:/downloads
    # username: admin
    # password: adminadmin

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/.config/jackett:/config
      - ${ROOT}/Downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/.config/sonarr:/config
      - ${ROOT}/Public/Series:/tv
      - ${ROOT}/Downloads:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/.config/radarr:/config
      - ${ROOT}/Public/Movies:/movies
      - ${ROOT}/Downloads:/downloads

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/.config/bazarr:/config
      - ${ROOT}/Public/Movies:/movies
      - ${ROOT}/Public/Series:/tv

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/.config/jellyfin:/config
      - ${ROOT}/Public/Movies:/data/movies
      - ${ROOT}/Public/Series:/data/tvshows