---
- vars:
      app_name: cloudflared
      config:
          root: '{{ env.JARVIS_CONFIGS_DIR }}/{{ app_name }}'
  block:
      - name: '{{ app_name | upper }}: Configure Directories'
        file:
            path: '{{ config.root }}'
            state: directory
            mode: '0755'

      - name: '{{ app_name | upper }}: Create docker-compose.yml'
        copy:
            dest: '{{ config.root }}/docker-compose.yml'
            content: |-
                services:
                  {{ app_name }}:
                    container_name: {{ app_name }}
                    image: cloudflare/cloudflared:latest
                    network_mode: host
                    restart: unless-stopped
                    command: tunnel run --token {{ env.RITIK_CF_TUNNEL_TOKEN }}
                    logging:
                      driver: "json-file"
                      options:
                        max-size: "10m"
                        max-file: "3"
            mode: '0644'
        register: cf_compose
        no_log: true

      - name: '{{ app_name | upper }}: Deploy Container'
        command: docker compose up -d
        args:
            chdir: '{{ config.root }}'
        register: cf_deploy
        changed_when: "'Created' in cf_deploy.stderr or 'Recreated' in cf_deploy.stderr"

      - name: '{{ app_name | upper }}: Restart on Config Change'
        command: docker restart {{ app_name }}
        when: cf_compose is changed and cf_deploy is not changed
