name: ${JARVIS_CONTAINER_NAME}
services:
  redis:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    ports:
      - 6379:6379
    volumes:
      - ${JARVIS_CONFIGS}/${JARVIS_CONTAINER_NAME}/data:/data
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true