services:
  auth:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: quay.io/keycloak/keycloak
    restart: unless-stopped
    command: start
    ports:
      - 9090:8080
    environment:
      KC_HOSTNAME: ${JARVIS_CONTAINER_NAME}.${JARVIS_DOMAIN}
      KC_PROXY: edge
      KEYCLOAK_ADMIN: ${JARVIS_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${JARVIS_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      PROXY_ADDRESS_FORWARDING: true
    healthcheck:
      test: 
      - "CMD-SHELL"
      - |
        exec 3<>/dev/tcp/localhost/9000 &&
        echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 &&
        cat <&3 | tee /tmp/healthcheck.log | grep -q '200 OK'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}:/opt/keycloak/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.${JARVIS_DOMAIN}`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.service=${JARVIS_CONTAINER_NAME}
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
      - traefik.http.services.${JARVIS_CONTAINER_NAME}.loadbalancer.server.port=8080
      - traefik.http.services.${JARVIS_CONTAINER_NAME}.loadbalancer.passhostheader=true
      - traefik.http.middlewares.${JARVIS_CONTAINER_NAME}.forwardAuth.address=http://${JARVIS_CONTAINER_NAME}:8080
      - traefik.http.middlewares.${JARVIS_CONTAINER_NAME}.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.${JARVIS_CONTAINER_NAME}.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name
      - traefik.http.middlewares.${JARVIS_CONTAINER_NAME}.forwardauth.tls.insecureSkipVerify=true
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true