---
- name: Setup Local Environment
  hosts: local
  connection: local
  gather_facts: true
  tasks:
      - name: Install Ansible Requirements
        command: ansible-galaxy collection install -r requirements.yml --upgrade
        register: galaxy_install
        changed_when: "'Installing' in galaxy_install.stdout"

      - name: Environment Setup
        include_tasks: tasks/env.yml

- name: Deploy to Remote Proxmox
  hosts: proxmox
  gather_facts: true
  pre_tasks:
      - name: Restore Environment Variables
        set_fact:
            env: '{{ hostvars["local"]["env"] }}'
        no_log: true

  tasks:
      - name: Execute System Tasks
        include_tasks: 'tasks/system/{{ item }}.yml'
        loop: [update, automount]

      - name: Deploy instances
        include_tasks: '{{ instance_file }}'
        loop: "{{ lookup('fileglob', playbook_dir + '/tasks/instances/*.yml', wantlist=True) | sort }}"
        vars:
            skip: [apps]
        when: (skip | map('regex_replace', '^(.*)$', '_\\1_') | select('in', instance_file) | list | length) == 0
        loop_control:
            loop_var: instance_file
            label: '{{ instance_file | basename }}'
