services:
  oauth2-proxy:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: quay.io/oauth2-proxy/oauth2-proxy
    ports:
      - "4180:4180"
    volumes:
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}:/etc/oauth2-proxy
    environment:
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_COOKIE_SECRET=${JARVIS_COOKIE_SECRET}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.${JARVIS_DOMAIN}`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.service=api@internal
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
    networks:
      - proxy

networks:
  proxy:
    external: true