services:
  alist:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: xhofe/alist:latest-ffmpeg
    restart: unless-stopped
    ports:
      - 5244:5244
    environment:
      TZ: ${JARVIS_TZ}
      PUID: ${JARVIS_PUID}
      PGID: ${JARVIS_PGID}
      UMASK: 022
    volumes:
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}:/opt/alist/data
      - ${JARVIS_DRIVE_ROOT}:/mnt
      - ${HOME}:/home
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.${JARVIS_DOMAIN}`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
      - traefik.http.services.${JARVIS_CONTAINER_NAME}.loadbalancer.server.port=5244
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true