services:
  homarr:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: ghcr.io/ajnart/homarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 7575:7575
    environment:
      TZ: ${JARVIS_TZ}
      DEFAULT_COLOR_SCHEME: dark
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/configs:/app/data/configs
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/icons:/app/public/icons
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_DOMAIN}`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
      - traefik.http.services.${JARVIS_CONTAINER_NAME}.loadbalancer.server.port=7575
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true