services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr
    restart: unless-stopped
    ports:
      - '7575:7575'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JARVIS_CONFIG_ROOT}/homarr/configs:/app/data/configs
      - ${JARVIS_CONFIG_ROOT}/homarr/icons:/app/public/icons
      - ${JARVIS_CONFIG_ROOT}/homarr/data:/data
    networks:
      - caddy

networks:
  caddy:
    external: true