name: ${JARVIS_CONTAINER_NAME}
services:
  orbital-sync:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: mattwebbio/orbital-sync
    security_opt:
      - no-new-privileges:true
    environment:
      PRIMARY_HOST_BASE_URL: http://pihole
      PRIMARY_HOST_PASSWORD: ${JARVIS_ADMIN_PASSWORD}
      # SECONDARY_HOSTS_1_BASE_URL: 'https://pihole2.example.com'
      # SECONDARY_HOSTS_1_PASSWORD: 'your_password2'
      INTERVAL_MINUTES: 60
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true