services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JARVIS_CONFIG_ROOT}/portainer:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`portainer.myjarvis.in`)
      - traefik.http.routers.pihole.entrypoints=websecure
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=letsencrypt
    networks:
      - proxy

networks:
  proxy:
    external: true