services:
  portainer:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.${JARVIS_DOMAIN}`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
      - traefik.http.services.${JARVIS_CONTAINER_NAME}.loadbalancer.server.port=9000
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true