services:
  codeserver:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: codercom/code-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    build:
      dockerfile: Dockerfile
    environment:
      DOCKER_USER: ${USER}
      PASSWORD: ${JARVIS_PASSWORD}
    ports:
      - 8888:8080
    user: ${JARVIS_PUID}:${JARVIS_PGID}
    volumes:
      - /:/host
      - ${HOME}:/home/coder/home
      - ${HOME}/.gitconfig:/home/coder/.gitconfig
      - ${HOME}/.gitignore_global:/home/coder/.gitignore_global
      - ${HOME}/.ssh:/home/coder/.ssh
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}:/home/coder/.config/code-server
      - ${JARVIS_CONFIG_ROOT}:/home/coder/AppConfigs
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.myjarvis.in`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
    networks:
      - proxy

networks:
  proxy:
    external: true