[local]
localhost ansible_connection=local ansible_python_interpreter="{{ ansible_playbook_python }}"

[coding]
oracle ansible_host=144.24.124.129
proxmox ansible_host=192.168.68.240

[parents]
pve ansible_host=192.168.68.200 ansible_user=root
