- name: System Update
  hosts: jarvis
  gather_facts: yes
  become: true

  vars:
      update_stamp_path: /var/lib/apt/periodic/update-success-stamp

  tasks:
      - name: Check last update timestamp
        stat:
            path: "{{ update_stamp_path }}"
        register: update_stamp

      - name: Calculate hours since last update
        set_fact:
            hours_since_update: >-
                {{ 25 if not update_stamp.stat.exists else ((ansible_date_time.epoch|int - update_stamp.stat.mtime|int) // 3600) }}

      - name: Show last update status
        debug:
            msg: >-
                {{ 'First run - no previous update detected' if not update_stamp.stat.exists else 'Last system update was ' + hours_since_update|string + ' hours ago' }}

      - name: Exit if updated within last 24 hours
        meta: end_play
        when: hours_since_update|int < 24

      - name: Perform system update
        apt:
            update_cache: yes
            upgrade: yes
            autoremove: yes
            autoclean: yes

      - name: Ensure update timestamp file
        file:
            path: "{{ update_stamp_path }}"
            state: touch
            mode: "0644"

      - name: Show update summary
        debug:
            msg: "System update completed."
