name: ${JARVIS_CONTAINER_NAME}
services:
  cloudflared:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    user: ${JARVIS_PUID}:${JARVIS_PGID}
    security_opt:
      - no-new-privileges:true
    environment:
      TUNNEL_TOKEN: ${JARVIS_CF_TUNNEL_TOKEN}
    volumes:
      - ${JARVIS_CONFIGS}/${JARVIS_CONTAINER_NAME}:/etc/cloudflared
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true