services:
  auth:
    container_name: ${JARVIS_CONTAINER_NAME}
    image: ghcr.io/goauthentik/server
    restart: unless-stopped
    command: server
    environment:
      TZ: ${JARVIS_TZ}
      AUTHENTIK_ERROR_REPORTING__ENABLED: true
      AUTHENTIK_SECRET_KEY: ${JARVIS_AUTH_SESSION_KEY}
      # AUTHENTIK_COOKIE_DOMAIN: ${JARVIS_DOMAIN}
      AUTHENTIK_REDIS__HOST: ${JARVIS_AUTH_REDIS_HOST}
      AUTHENTIK_REDIS__PORT: ${JARVIS_AUTH_REDIS_PORT}
      AUTHENTIK_REDIS__PASSWORD: ${JARVIS_AUTH_REDIS_PASSWORD}
      AUTHENTIK_POSTGRESQL__HOST: ${JARVIS_AUTH_POSTGRESQL_HOST}
      AUTHENTIK_POSTGRESQL__USER: ${JARVIS_AUTH_POSTGRESQL_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${JARVIS_AUTH_POSTGRESQL_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${JARVIS_AUTH_POSTGRESQL_PASSWORD}
      AUTHENTIK_EMAIL__HOST: smtp.gmail.com
      AUTHENTIK_EMAIL__PORT: 587
      AUTHENTIK_EMAIL__USERNAME: ${JARVIS_EMAIL}
      AUTHENTIK_EMAIL__PASSWORD: ${JARVIS_AUTH_GOOGLE_APP_PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: false
      AUTHENTIK_EMAIL__USE_SSL: false
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: ${JARVIS_CONTAINER_NAME}@${JARVIS_DOMAIN}
    volumes:
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/media:/media
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/templates:/templates
    ports:
      - 9080:9000
    labels:
      - traefik.enable=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.rule=Host(`${JARVIS_CONTAINER_NAME}.${JARVIS_DOMAIN}`) || HostRegexp(`{subdomain:[a-z0-9-]+}.$JARVIS_DOMAIN`) && PathPrefix(`/outpost.goauthentik.io/`)
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.middlewares=${JARVIS_CONTAINER_NAME}@docker
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls=true
      - traefik.http.routers.${JARVIS_CONTAINER_NAME}.tls.certresolver=${JARVIS_CERT_RESOLVER}
      - traefik.http.services.${JARVIS_CONTAINER_NAME}.loadbalancer.server.port=9000
      - traefik.http.middlewares.${JARVIS_CONTAINER_NAME}.forwardAuth.address=http://${JARVIS_CONTAINER_NAME}:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.${JARVIS_CONTAINER_NAME}.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.${JARVIS_CONTAINER_NAME}.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

  auth-worker:
    container_name: ${JARVIS_CONTAINER_NAME}-worker
    image: ghcr.io/goauthentik/server
    restart: unless-stopped
    command: worker
    user: root
    environment:
      TZ: ${JARVIS_TZ}
      AUTHENTIK_ERROR_REPORTING__ENABLED: true
      AUTHENTIK_SECRET_KEY: ${JARVIS_AUTH_SESSION_KEY}
      # AUTHENTIK_COOKIE_DOMAIN: ${JARVIS_DOMAIN}
      AUTHENTIK_REDIS__HOST: ${JARVIS_AUTH_REDIS_HOST}
      AUTHENTIK_REDIS__PORT: ${JARVIS_AUTH_REDIS_PORT}
      AUTHENTIK_REDIS__PASSWORD: ${JARVIS_AUTH_REDIS_PASSWORD}
      AUTHENTIK_POSTGRESQL__HOST: ${JARVIS_AUTH_POSTGRESQL_HOST}
      AUTHENTIK_POSTGRESQL__USER: ${JARVIS_AUTH_POSTGRESQL_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${JARVIS_AUTH_POSTGRESQL_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${JARVIS_AUTH_POSTGRESQL_PASSWORD}
      AUTHENTIK_EMAIL__HOST: smtp.gmail.com
      AUTHENTIK_EMAIL__PORT: 587
      AUTHENTIK_EMAIL__USERNAME: ${JARVIS_EMAIL}
      AUTHENTIK_EMAIL__PASSWORD: ${JARVIS_AUTH_GOOGLE_APP_PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: false
      AUTHENTIK_EMAIL__USE_SSL: false
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: ${JARVIS_CONTAINER_NAME}@${JARVIS_DOMAIN}
    ports:
      - 1000:1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/media:/media
      - ${JARVIS_CONFIG_ROOT}/${JARVIS_CONTAINER_NAME}/templates:/templates
    networks:
      - ${JARVIS_PROXY_DOCKER_NETWORK}

networks:
  proxy:
    external: true