services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${JARVIS_CF_TUNNEL_TOKEN}
    volumes:
      - ${JARVIS_CONFIG_ROOT}/cloudflared:/etc/cloudflared
    networks:
      - proxy

networks:
  proxy:
    external: true