services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    network_mode: host
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${JARVIS_CLOUDFLARED_TOKEN}
    volumes:
      - ${JARVIS_CONFIG_ROOT}/cloudflared:/etc/cloudflared