version: "3.8"
services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge
    network_mode: host
    restart: unless-stopped
    volumes:
      - /media/drive1/.config/homebridge:/homebridge
    