services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: host
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=${JARVIS_PUID}
      - PGID=${JARVIS_PGID}
      - TZ=${JARVIS_TZ}
    volumes:
      - ${JARVIS_CONFIG_ROOT}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro