version: "3.8"
services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=3000
      - HOMEBRIDGE_CONFIG_UI_AUTH=1
      - HOMEBRIDGE_CONFIG_UI_USERNAME=ritik
      - HOMEBRIDGE_CONFIG_UI_PASSWORD=112233
    volumes:
      - ${ROOT}/.config/homebridge:/homebridge

version: "3.8"
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/.config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host